filebeat.inputs:
  - type: docker
    containers:
      path: "/usr/share/dockerlogs/data"
      stream: "all"
      ids:
        - "*"
  - type: log
    paths:
      - /logs/*.log

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

setup.kibana:
  host: "localhost:5601"
  username: "tanyginda"
  password: "tanyginda"
  
output.logstash:
  hosts: ["127.0.0.1:5044"]
  
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
